services:
  - mysql
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('dev') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
install:
  - composer require --dev phpunit/phpunit ^5.7
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit --version
script: $TRAVIS_BUILD_DIR/vendor/bin/phpunit
language: php
php:
  - '5.6'
  - '7.0'
after_failure: "cat /tmp/icehrm.test.log"
