services:
  - mysql
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('dev') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - nightly
after_failure: "cat /tmp/icehrm.test.log"
